groups:
  - name: gpu_memory_alerts
    rules:
      - alert: GPUMemoryUsageHigh
        # Condition for alerting
        expr: (nvidia_smi_memory_used_bytes / nvidia_smi_memory_total_bytes) * 100 > 80
        for: 2s
        labels:
          severity: critical
        annotations:
          summary: "GPU Memory usage is high on instance {{ $labels.instance }}"
          description: "GPU {{ $labels.uuid }} on instance {{ $labels.instance }} has reached the threshold of 80% memory usage ({{ $value }}%)."
