global:
  scrape_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Host Metrics
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100'] #Host monitor deployed through Docker Container
      - targets: ['10.147.19.160:9835'] # GPU Metrics

  #Containers Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']