global:
  scrape_interval:     10s
  evaluation_interval: 2s

rule_files:
  - "gpu_mem_rules.yaml"


#Alertmanager Server
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 10.147.19.160:9093


scrape_configs:
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']

  # Host Metrics
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100'] #Host monitor deployed through Docker Container
      - targets: ['10.147.19.160:9835'] # GPU Metrics

  #Containers Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']